# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python:
      version: "3.10"
    sphinx:
      version: "4.4.0"

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py

# Optionally declare the Python requirements required to build your docs
python:
  install:
    - requirements: docs/requirements.txt

# Build triggers
trigger:
  # Build on each push to main branch
  - master
  # Build when a tag is pushed in the format d+.d+.d+
  - tag: '/^\d+\.\d+\.\d+$/'
    # Specify the version that should be built for the tag
    version: '{tag}'
    # If tag is not provided, use "latest" as the default version
    fallback-version: latest